### ISSUE TITLE
设置最多展示行数

### ISSUE THREAD

**Issue by QinAndroid** [donkingliang/LabelsView#14]
您好，我在代码中没有找到对最大行数的设置方法，请问 怎么设置最大显示行数？

**Comment by donkingliang** [comment]
你好，这个控件没有设置最大显示行数的功能。

**Comment by QinAndroid** [comment]
你这边方便添加一个吗？

**Comment by QinAndroid** [comment]
![default](https://user-images.githubusercontent.com/6628144/48529005-3da50f00-e8cc-11e8-92a6-4181b9a9ff16.png)

**Comment by donkingliang** [comment]
你好，设置最大显示行数(maxLines)的功能已经加上了。新版本：1.4.6。
