### ISSUE TITLE
点击

### ISSUE THREAD

**Issue by wangfufu** [donkingliang/LabelsView#18]
能否设置了默认选中后不可点击

**Comment by donkingliang** [comment]
对于点击，没有做限制。对于选中状态，如果你设置了某个item为必选项，那么这个item会一直是选中状态，不能取消。

**Comment by donkingliang** [comment]
如果你希望item选中后不能点击，你可以这OnLabelClickListener的回调中做判断，如果是选中状态，这个方法就什么都不做就可以啦。
