### ISSUE TITLE
少一条数据

### ISSUE THREAD

**Issue by PickyQiu** [donkingliang/LabelsView#19]
小米note3，高度设置成wrap_content，9条数据的时候少了一条。当高度设置成固定高度的时候能显示出来！

**Comment by donkingliang** [comment]
多谢你的反馈。旧版本的测量，在特殊情况下可能测量错误。这个bug我已经了修复，建议你使用新版本再尝试一下，谢谢。

**Comment by PickyQiu** [comment]
感谢你的回复，1.4.7是不是没传成功？这边下载不下来！

**Comment by donkingliang** [comment]
多谢你的反馈。可能是因为网络问题自动构建失败。我重新构建了一下 ，自己测试过可以引用到依赖了。你可以重新尝试一下。
