### ISSUE TITLE
在Listview中使用，在低分辨率手机上List的最后两个元素不显示了，在高分辨中没有这个问题，求解

### ISSUE THREAD

**Issue by aiceking** [donkingliang/LabelsView#2]

**Comment by donkingliang** [comment]
LabelsView在列表中使用也不应该有这样的问题啊。我觉得是不是你的ListView使用有问题啊。你可以查一下你的ListView的代码。
如果你还是解决不了这个问题，或者是发现确实是LabelsView的问题，欢迎你把问题反馈给我。QQ:1043214265。谢谢！
