### ISSUE TITLE
能设置字体加粗吗？

### ISSUE THREAD

**Issue by chao9267** [donkingliang/LabelsView#21]
能设置字体加粗吗？

**Comment by donkingliang** [comment]
你用下面这种方法设置标签数据。
labelsView.setLabels(labelDatas, new LabelsView.LabelTextProvider<String>() {
            @Override
            public CharSequence getLabelText(TextView label, int position, String data) {
               // 这里的label就是标签View。你可以在这里用代码设置它的任何样式或属性。
                label.setTypeface(Typeface.defaultFromStyle(Typeface.BOLD));
                return data;
            }
        });
