### ISSUE TITLE
可能超出边界

### ISSUE THREAD

**Issue by lucers** [donkingliang/LabelsView#22]
onLayout方法中,contentWidth = right - left,如果有设置了paddingRight的情况下,contentWidth应该再减去paddingRight的距离,才是右边的边界X

**Comment by donkingliang** [comment]
在定位子View的时候有处理Layout的padding了。所以应该不会出现超出边界的问题。

**Comment by lucers** [comment]
好的,谢谢,我看到了,在判断contentWidth的时候你有加上paddingRight,
