### ISSUE TITLE
希望简化 AndroidManifest.xml 文件。

### ISSUE THREAD

**Issue by lijunzz** [donkingliang/LabelsView#23]
[AndroidManifest.xml](https://github.com/donkingliang/LabelsView/blob/master/labels/src/main/AndroidManifest.xml) 中移除掉**application**，开发者可以根据自己需求添加：
```xml
android:allowBackup="true"
android:supportsRtl="true"
```

**Comment by donkingliang** [comment]
多谢反馈。这个我会在后面的优化中去掉的。
