### ISSUE TITLE
Dear 大佬

### ISSUE THREAD

**Issue by luncle** [donkingliang/LabelsView#24]
您的方法里有选择之后的函数，但当我选择之后 突然有几个点了取消，但是这个取消的事件们可以同步到获取的data的那个list 上吗，，简而言之就是好像只能第一次全部点击正确？

**Comment by luncle** [comment]
或者说就是 选中时 实时传到textview上

**Comment by luncle** [comment]
取消选中的时候 也从text 上取消下来

**Comment by donkingliang** [comment]
我不太明白你描述的是什么意思？
如果你是想监听data的选中和取消，我有提供方法设置监听的。你可以在监听器里做你要做的事情。
