### ISSUE TITLE
不能居中显示

### ISSUE THREAD

**Issue by xmy1231** [donkingliang/LabelsView#25]
文字不能居中显示。

**Comment by donkingliang** [comment]
你说的是标签相对于布局居中吗？因为我但是设置就是标签从左到右流式排版的，所以没有做居中处理。

**Comment by xmy1231** [comment]
@donkingliang  大佬， 可以做一下居中处理吗？ 排版不太美观

**Comment by my29** [comment]
解决了吗？当一行超过了，整体标签在当前行居中

**Comment by donkingliang** [comment]
处理这个的话会影响整个控件的排版方式的，所以我没有对这个做处理。

**Comment by xmy1231** [comment]
大佬，加上这句试试
![1561965733506](https://user-images.githubusercontent.com/10206252/60417912-27a64d80-9c14-11e9-915a-cfa350554ea6.jpg)

**Comment by donkingliang** [comment]
1.6.0版本支持设置标签宽高和文本显示方向。
