### ISSUE TITLE
请问怎么设置列表中某个条目不能点击

### ISSUE THREAD

**Issue by BoyYangyang** [donkingliang/LabelsView#31]

**Comment by donkingliang** [comment]
你是想设置某个项为选中状态，不能取消吗？可以设置某个项为必选。必选的项是一直选中的，不能取消。
没有设置某个项不能点击的方法。如果你一定要让某个项不能点击，可以有一种方法，在LabelTextProvider里去掉label的点击监听。
labelsView.setLabels(testList, new LabelsView.LabelTextProvider<TestBean>() {
            @Override
            public CharSequence getLabelText(TextView label, int position, TestBean data) {
                // 取消点击监听
                label.setOnClickListener(null);
                return data.getName();
            }
        });

**Comment by ZoeTTTT** [comment]
补充楼上，若想重新启用之前禁用过的点击事件可以重新调用labelsView.setLabels(testList),启用点击事件的关键方法是ensureLabelClickable(),但此方法是private的，故可以按需调用相关包含这个方法的public方法。
最近在项目中搞了个类似某宝的多规格选择，还好使用这个基本可以满足需求~~

**Comment by LhtIverson** [comment]
> 补充楼上，若想重新启用之前添加过的点击事件可以重新调用labelsView.setLabels（testList），启用点击事件的关键方法是ensureLabelClickable（），但此方法是private的，故可以按需调用相关包含这个方法的public方法。
> 最近在项目中从事了一个类似某宝的多规格选择，还好使用这个基本可以满足需求~~

您好 我现在也有这个多规格选择的项目 没搞出来 能不能请教一下  谢谢了
