### ISSUE TITLE
在SINGLE_IRREVOCABLY模式下能不能取消默认值（默认选中第一个） 

### ISSUE THREAD

**Issue by Linnnnnn** [donkingliang/LabelsView#32]
如题：
谢大佬

**Comment by donkingliang** [comment]
不能，SINGLE_IRREVOCABLY必须是有一个必须的。但是你可以在setLabels之后调用 labelsView.setSelects(new int[]{});设置选中的项。你只要传个空的数组就可以都不选中了。

**Comment by Linnnnnn** [comment]
> 不能，SINGLE_IRREVOCABLY必须是有一个必须的。但是你可以在setLabels之后调用 labelsView.setSelects(new int[]{});设置选中的项。你只要传个空的数组就可以都不选中了。

谢谢，已解决
