### ISSUE TITLE
标签的长按事件

### ISSUE THREAD

**Issue by TReturn** [donkingliang/LabelsView#37]
作者你好，能否增加labels长按事件的监听，感谢

**Comment by donkingliang** [comment]
你好，多选反馈，这个需求可以在以后的版本中添加。
现在也可以在LabelTextProvider里给label设置长按监听实现同样的效果。
labelsView.setLabels(testList, new LabelsView.LabelTextProvider() {
@override
public CharSequence getLabelText(TextView label, int position, TestBean data) {
// 设置长按
label.setOnLongClickListener();
return data.getName();
}
});

**Comment by TReturn** [comment]
好的，非常感谢。这个框架很好用，我推荐给我同事，他也用了
