### ISSUE TITLE
正常样式和选中样式不生效

### ISSUE THREAD

**Issue by QiaoYang0923** [donkingliang/LabelsView#43]
您好,我根据您的文档,在xml中配置了
 app:labelBackground="@drawable/label_bg"
        app:labelTextColor="@drawable/label_text_color"
但是在点击label的时候并没有出现设置的效果,没有任何反应,

setOnLabelClickListener 这个监听是有效的.

**Comment by donkingliang** [comment]
你的drawable是根据我文中写的吗？我例子中的drawable是选中时的效果，不是点击时的效果。如果你想选中标签，还要设置selectType属性

**Comment by QiaoYang0923** [comment]
找到问题了isIndicator=true,谢谢
