### ISSUE TITLE
有没有取消选中的单个API

### ISSUE THREAD

**Issue by AttackPangHu** [donkingliang/LabelsView#47]
看到有个clearAll的 有没有取消单个的？这里有个需求是个其他个列表做联动的，其他列表删除了，这边选中的状态要改为未选中

**Comment by donkingliang** [comment]
没有取消单个选中的API，但是有设置选中的API，所以你这个效果可以通过保存选中的项，然后在需要取消选中时，只要从选中的列表中移除取消的项，再重新设置选中列表就可以了。

**Comment by AttackPangHu** [comment]
我没有重新setSelect，那样的话下面的重新选中之后会走onChange监听，相当于你上面联动的列表又走了一次，我现在用了getChildAt(indexOf).performClick()实现了

**Comment by donkingliang** [comment]
让标签主动促发一次点击，这种方式也很巧妙。
