### ISSUE TITLE
角标的奇怪BUG

### ISSUE THREAD

**Issue by AttackPangHu** [donkingliang/LabelsView#49]
setOnLabelClickListener  我给标签设置了点击事件，点击时根据position去移动对应位置的label，但是当我删除第一个，也就是角标是0的view时，之后删除第一个，角标全部变成了1，然后删到最后只剩最后个VIew时就报空了

**Comment by donkingliang** [comment]
你是怎么删除label的，直接removeView，还是remove数据后重新setLabels。应该要用后者，删除数据需要先改变数据源，在重新设置标签列表。
