### ISSUE TITLE
只设置字符串不方便

### ISSUE THREAD

**Issue by zhangyifanqq** [donkingliang/LabelsView#5]
您好：提个建议哈。能否设置label是Arraylist<Object> 呢，因为只设置String实在不方便，这个字符串的id、类型等等属性需要上传。然后获取的时候直接获取选中条目的对象就方便多了。

**Comment by donkingliang** [comment]
因为LabelsView里的每个item都是一个TextView，所以我就只让它，能设置String类型的数据，如果要让他可以设置和返回任何类型的数据的话，需要改动item的显示更新等逻辑。

多谢你的反馈。我会考虑对它进行优化修改，并且会尽量使它兼容原来的版本。

**Comment by donkingliang** [comment]
新版本已支持设置任何类型的数据。多谢你的反馈。
