### ISSUE TITLE
com.donkingliang.labels.LabelsView里边的一排tags如何让他居中？

### ISSUE THREAD

**Issue by cngkqy** [donkingliang/LabelsView#50]
![image](https://user-images.githubusercontent.com/16894280/103095017-15a34080-463a-11eb-80bb-ab37f6561325.png)
作者你好，我在使用你的控件，但是发现了一个问题，就是我设置了一排4个lables，控件宽度设置成了android:layout_width="match_parent"
但是加载出来的lables不居中，而是左路对齐，请问这是bug么？还是需要设置什么属性，我找了一下没找到，烦请告知，不胜感激！
代码粘贴如下：
<com.donkingliang.labels.LabelsView
            android:id="@+id/labvMessageType"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:isIndicator="false"
            app:labelBackground="@drawable/label_bg"
            app:labelTextColor="@drawable/label_text_color"
            app:labelTextPaddingBottom="5dp"
            app:labelTextPaddingLeft="10dp"
            app:labelTextPaddingRight="10dp"
            app:labelTextPaddingTop="5dp"
            app:labelTextSize="14sp"
            app:layout_constraintTop_toBottomOf="@+id/linearLayout"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:lineMargin="10dp"
            app:maxLines="3"
            app:maxSelect="4"
            app:minSelect="0"
            app:selectType="MULTI"
            app:wordMargin="10dp"
            android:background="@color/red"
            />

**Comment by donkingliang** [comment]
这不是bug，LabelsView的排列就是左对齐的，而且LabelsView没有方法可以设置一行只能显示4个lables。如果你的列表最多只有4个标签，那么你可以设置LabelsView的宽为wrap_content，然后让它相对于父布局居中。

**Comment by cngkqy** [comment]
试了下，可以居中了，感谢~
