### ISSUE TITLE
长按标签在右上角显示删除icon，不好实现

### ISSUE THREAD

**Issue by 24suixinsuoyu** [donkingliang/LabelsView#61]
长按监听里，onLabelLongClick，给单独的 TextView 设置背景（setBackground，会拉伸）或者 setCompoundDrawable（会截断），或者在整个的 labelsView 里面 addView(size 变化时位置不跟随当前的 label) 效果都不理想。。作者有没有比较好的思路呢？

**Comment by donkingliang** [comment]
确实不好设置。你可以试一下使用[BadgeView](https://github.com/qstumn/BadgeView)给标签添加角标。或者你直接下载源码修改，把label由TextView改成其他view。源码只有一个类，修改比较简单
