### ISSUE TITLE
4个元素时候，onMeasure 的判断有问题，导致只显示3个。

### ISSUE THREAD

**Issue by Wanchen7** [donkingliang/LabelsView#7]
传入4个label

![2018-03-21 2 21 47](https://user-images.githubusercontent.com/23703126/37696698-7ae75e9c-2d13-11e8-85ca-7e1e71988f10.png)

maxWidth 正好等于 lineWidth + view.getMeasuredWidth() 。没有显示最后一个

**Comment by JuanTop** [comment]
这个算法有点问题，onMeasure 和 onLayout 的结果不一样导致出现少行的情况，你要在 onMeasure 里面把if (!begin) {
                lineWidth += mWordMargin;
            } else {
                begin = false;
            }这个移到判断条件前面来，如果不是第一个，先把间隔宽度加上，不然到一行末尾就有可能会出现测量结果出现错误。

**Comment by donkingliang** [comment]
感谢反馈问题。这个问题的确是我疏忽了，现在已经改正。谢谢！

**Comment by DuoQing666** [comment]
1.4.6 还有这个问题呢。。我现在就是 布局显示少一行数据。。 很明显的高度计算不太对。
@donkingliang
