### ISSUE TITLE
能否设置每个标签的样式？

### ISSUE THREAD

**Issue by oksimple** [donkingliang/LabelsView#9]
比如每个标签的圆角角度。还有动态删除某个标签的功能好实现嘛？

**Comment by donkingliang** [comment]
你的这个需求，用我的这个LabelsView不好实现。因为LabelsView就算一个普通的标签列表，它的样式都是统一设置好的。
你用多item的RecyclerView或者是[flexbox-layout](https://github.com/google/flexbox-layout)可能会更好。
